# Site settings
title: Jason Merino
description: "I build web apps and I have <b>fun</b> doing it."
baseurl: ""
url: "http://jasonmerino.me"
username: "jasonmerino"
disqus:
  shortname: "jasonmerino"

# Build settings
markdown: redcarpet
permalink: pretty
