# Site settings
title: Jason Merino
description: "I build web apps and I have <b>fun</b> doing it."
baseurl: ""
url: "http://yourdomain.com"
username: "jasonmerino"

# Build settings
markdown: redcarpet
permalink: pretty
